### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by RWOverdijk** [avocode/nachos-ui#16]
The links in the docs are broken, they all bring me to a 404 page.

https://avocode.com/nachos-ui/docs#!.

example: https://avocode.com/nachos-ui/Showcase/Input

**Comment by petrbrzek** [comment]
@RWOverdijk I'm sorry. We deployed a new version of our website and broke the Nachos docs. It should work now. https://avocode.com/nachos-ui/docs/#!/search/input

**Comment by RWOverdijk** [comment]
Wooo
