### ISSUE TITLE
Nachos does not works with EXPO

### ISSUE THREAD

**Issue by josenaves** [avocode/nachos-ui#27]
I'm getting some errors (warnings) after I try to add nachos-ui to an EXPO project.

17:41:53: jest-haste-map: @providesModule naming collision:
17:41:53:   Duplicate module name: DocumentSelectionState
17:41:53:   Paths: /home/josenaves/Projects/nachos-expo/node_modules/react-native/Libraries/vendor/document/selection/DocumentSelectionState.js collides with /home/josenaves/Projects/nachos-expo/node_modules/nachos-ui/node_modules/react-native/Libraries/vendor/document/selection/DocumentSelectionState.js
17:41:53: 
17:41:53: This warning is caused by a @providesModule declaration with the same name across two different files.
17:41:53: jest-haste-map: @providesModule naming collision:
17:41:53:   Duplicate module name: Animation
17:41:53:   Paths: /home/josenaves/Projects/nachos-expo/node_modules/react-native/Libraries/Animated/src/animations/Animation.js collides with /home/josenaves/Projects/nachos-expo/node_modules/nachos-ui/node_modules/react-native/Libraries/Animated/src/animations/Animation.js

My package.json:
{
  "name": "nachos-expo",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "^22.0.0",
    "react-native-scripts": "1.7.0",
    "react-test-renderer": "16.0.0-beta.5"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^22.0.2",
    "nachos-ui": "^0.1.2",
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5"
  }
}

**Comment by LewisRogers** [comment]
I ran into similar issues when trying to use Yarn as the packager, there's a dependency mismatch somewhere perhaps? Rebuilding and running the project with npm resolved the issue for me.

**Comment by mattapperson** [comment]
This issue is being tracked now in #34. Closing.
