### ISSUE TITLE
Style the footer text of Nachos ui card

### ISSUE THREAD

**Issue by Taimoormk** [avocode/nachos-ui#28]
I would like to style the text as it appears in the following screenshot attached, I am using Nachos UI card. I am able to style other elements of the Nachos UI card as such but unable to do so for the text in the footer section, thank you for your help.

<img width="177" alt="screen shot 2017-11-30 at 10 01 21" src="https://user-images.githubusercontent.com/27800340/33414998-c2a8d0f4-d5b5-11e7-9de4-5e8fc37b17c5.png">

**Comment by shokimble** [comment]
Supply JSX to the footerContent prop. Eg:

footerContent={<View><Text>{item.name}</Text><Strong>${item.price}</Strong></View>}

You can then apply styles to those supplied elements

**Comment by mattapperson** [comment]
This seems to be answered so I am closing now. If there is still an issue feel free to re-open :)
