### ISSUE TITLE
Duplicate module name: react-native-vector-icons

### ISSUE THREAD

**Issue by casperle** [avocode/nachos-ui#3]
Hi,
I already installed nachos-ui and when I am trying to start application I get this error:
```
This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: [...]/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with [...]/node_modules/nachos-ui/node_modules/react-native/local-cli/core/__fixtures__/files/package.json
```
Any ideas?

**Comment by casperle** [comment]
I tried it with react-native v0.39, v0.40 and v0.41. It is working only with version 0.40. The latest stable version is 0.41, so I had to install `rninit` package to set up a project with a correct version of react-native.
Can you please make it compatible with newer versions? Thank you.

**Comment by renekopcem** [comment]
I've just tried to update the React Native to v0.41, downgrade to v0.39, and both versions work. It looks like a different issue from what I see on StackOverflow and Github - http://stackoverflow.com/questions/38885760/react-native-packager-failure-duplicate-module-name
https://github.com/oblador/react-native-vector-icons/issues/379

**Comment by petrbrzek** [comment]
@casperle I changed the package.json to accept newer versions of React Native (https://github.com/avocode/nachos-ui/blob/master/package.json#L41). Can you try it out, please?

**Comment by casperle** [comment]
@petrbrzek did you published the changes into npm? Because it is installing the version before your changes.

**Comment by casperle** [comment]
@renekopcem I tried all the variants and I get the same error all the time. There is a collision between versions of react-native in the dependency of nachos-ui and what I am using in my project.

**Comment by petrbrzek** [comment]
@casperle I didn't, thanks. Published now as 0.1.1.

**Comment by jurajkrivda** [comment]
RN 0.38, Nachos 0.1.1 same problem

**Comment by casperle** [comment]
So here is the answer. If you have installed the same version of RN as the dependency in nachos-ui (>=0.40.0), everything works fine. I tried every scenario with a new project, not downgrade or upgrade.
@petrbrzek Now it is working fine, because `npm` is not installing the other version of RN as a dependency in nachos-ui, but it is using the installed one.

For me it is not working with lower version of RN as 0.40.0. In that scenario there is always an error with version mismatch or naming collision. It is not only in `react-native-vector-icons`, but also in other packages where is not the same version.

@petrbrzek I think there is two ways to fix it. First, you can delete the dependency of RN from `package.json` and warn people that they have to install RN as a dependency of their project - I don't exactly know how it will work when they want to use it on web of with lower version of RN. The second opinion is that you can make a notice somewhere that people can use `nachos-ui` only with newer versions of RN as v0.40.0 included.

**Comment by petrbrzek** [comment]
@casperle Thanks for your message. As there is a breaking change in RN 0.40.0, I'll probably choose the second option and add a notice that this kit requires RN `>=0.40.0`.

**Comment by petrbrzek** [comment]
Info has been added https://github.com/avocode/nachos-ui/commit/ca7de99428970d8d021df08675a7c99d0c62ebac

**Comment by roderickfung** [comment]
i'm using 0.43.3 and it's giving me the same errors.

**Comment by wv1124** [comment]
RN 0.43.4 face the same issue

**Comment by batjko** [comment]
Same with RN 0.50 (via the `create-react-native-app` cli, which uses Expo).

No work on this for half a year and there are also two other issues open for what seems to be the same issue. Given the CRNA popularity, is it fair to say this issue won't be fixed, or the project is no longer being maintained?
