### ISSUE TITLE
Ambiguous module resolution

### ISSUE THREAD

**Issue by mohsalsaleem** [avocode/nachos-ui#32]
Ambiguous module resolution from `../index.js`: The name `react-native` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or blacklist files until there remains only one of these:
warning: the transform cache was reset.

  * `../node_modules/nachos-ui/node_modules/react-native/package.json` (package)
  * `../node_modules/react-native/package.json` (package)

**Comment by same07** [comment]
i have same issue here.. anyone?

**Comment by mattapperson** [comment]
This issue is being tracked now in #34. Closing as dupe
