### ISSUE TITLE
'react-native' dependency is not installed.

### ISSUE THREAD

**Issue by gabrielfaro97** [avocode/nachos-ui#34]
I'm having this issue when i try to use nachos with the tab-navigation template generated by expo: "'react-native' dependency is not installed." 

I used npm install --save nachos-ui cause i noticed that i can't use yarn to install nachos-ui (at least when i'm useing expo)

**Comment by mattapperson** [comment]
This issue is being tracked now in #34. Closing.

**Comment by silvestreh** [comment]
@mattapperson you just closed the issue you're tracking 😃

**Comment by mattapperson** [comment]
@silvestreh meh I ment #36 my mistake 😕
