### ISSUE TITLE
Issues revolving around the duplication of RN or React deps

### ISSUE THREAD

**Issue by taynefemple** [avocode/nachos-ui#36]
Saw a lot of comments about this and just wanted to post what worked for me.  My team is using yarn: 

cd node_modules
cd nachos-ui
cd node_modules
rm -rf react-native

Then from project folder:

yarn start --reset-cache

Still have a lot of yellow in the console, but it works.  I'm sure there's a better fix out there, but I thought this could help some blocked folks out there.

**Comment by vikas5914** [comment]
Thanks

**Comment by mattapperson** [comment]
This should be fixed with PR #36. If not please let me know!
