### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dantopa** [avocode/nachos-ui#51]
Is this working? I installed it on an expo project, and just tried to use a button. I injected the theme provider, but the button renders so badly. The font color is not white, also the background is not solid. Also I can't put icons. Also I tried to use themeManager to customize but themeManager can't be imported because it doesn't exist.

**Comment by mattapperson** [comment]
Can you provide a small code example of what your currently doing?

**Comment by dantopa** [comment]
```
import {ThemeProvider} from "nachos-ui";
import TestScreen from "./src/components/test";
export default class App extends React.Component {
  constructor() {
    super();
    this.state = {
      fontsAreLoaded: false
    }
  }

  async componentWillMount() {
    await Font.loadAsync({
      'Roboto': require('native-base/Fonts/Roboto.ttf'),
      'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
      'Material Icons': require('nachos-ui/assets/fonts/MaterialIcons.ttf')
    }, null);
    this.setState({fontsAreLoaded: true})
  }

  render() {
    const {fontsAreLoaded} = this.state;
    if (fontsAreLoaded) {
      return (
        <ThemeProvider>
          <TestScreen/>
        </ThemeProvider>);
    } else {
      return <AppLoading />
    }
  }
}
```

Then:
```
import React from "react";
import {StyleSheet, View, Image} from "react-native"
import Expo from "expo"
import {Button} from 'nachos-ui'

export default class TestScreen extends React.Component {
  constructor(props) {
    super(props);
  }

  sayHello() {
    console.log("hi");
  }

  render() {
    return (
      <View>
        <SimpleButton action={this.sayHello}/>
      </View>
    )
  }
}

const SimpleButton = props => {
  return (
    <View>
      <Button onPress={() => props.action()}
      type="primary">
        Hello
      </Button>
    </View>
  )
};
```

And this is what I'm getting;
![screenshot_20180915-144635](https://user-images.githubusercontent.com/5399452/45589103-6aea3680-b8f6-11e8-8a51-0ad6d63ee491.png)

It's a purple button with purple font, nothing like what I see on the documentation.
And the action isn't working at all, when I press the button nothing appears on my console. Also, the iconName only works with Material Icons, not with Ionicons as the docs says.

**Comment by dantopa** [comment]
I'm using:
"expo": "^27.0.1",
"nachos-ui": "^0.2.0-beta.1",
"react": "16.3.1",
"react-native": "~0.55.2",

**Comment by mattapperson** [comment]
Ah, so the docs in the repo should be updated to the beta, the published docs are for the last GA version of 0.1.2.

0.2.0 has a new theme, and new API to go along with it.

I have been busier then normal the last few weeks, I hope to get 0.2 to GA soon, but the next few weeks will also be nuts as I am moving soon 😕. Please pardon the mess during construction.

**Comment by harrisonlo** [comment]
Looking forward to the new API!

**Comment by sasivarnan** [comment]
@mattapperson Any place where I can access the docs for new API?

**Comment by wesguirra** [comment]
@mattapperson Any place where I can access the docs for new API?

**Comment by wesguirra** [comment]
@sasivarnan I think we can use this -> https://github.com/nachos-ui/nachos-ui/blob/master/src/components/Theme/ThemeProvider.md
