### ISSUE TITLE
Color won't update on Bubble

### ISSUE THREAD

**Issue by sophieheb** [avocode/nachos-ui#52]
The following code does not update the color of the Bubble. (#f0f0f0 should be grey) Screenshot attached.
```  
<Bubble ref = "animatedText"
          style = {{marginBottom:14}}
          arrowPosition='left'
          color='#f0f0f0'>
          { this.state.words }
</Bubble> 
```
<img width="332" alt="screen shot 2018-10-09 at 15 32 59" src="https://user-images.githubusercontent.com/17166619/46676531-a36cef80-cbd8-11e8-80cf-8ef205c97dee.png">

**Comment by mattapperson** [comment]
I am guessing you are on master? The docs are not fully updated for the new beta api. You will need to use bubbleStyle prop and pass in backgroundColor key inside that.

This change is done for perf reasons
