### ISSUE TITLE
Feature enhancement request: animation on progress bar

### ISSUE THREAD

**Issue by harrisonlo** [avocode/nachos-ui#53]
It would nice to have some animation on the progress component, like below:

![image](http://g.recordit.co/xeG8gicuaM.gif)

**Comment by mattapperson** [comment]
Perhaps it’s a gif issue, but to do that all you would need to do is change the progress value several times?

**Comment by harrisonlo** [comment]
Yeah the gif is a little laggy, but I meant having the old value slide to the new value. Changing the value manually multiple times is still a little clunky...

**Comment by mattapperson** [comment]
Ah gotcha. Yea I’ll look into that. Smoother animations overall would be very nice in Nachos
