### ISSUE TITLE
Can you use Nachos-ui with Redux-Forms

### ISSUE THREAD

**Issue by nielswh** [avocode/nachos-ui#8]
Great UI Kit.

My one question is do you know if the components developed here are compatible with Redux-Form? (http://redux-form.com/)

Thanks,
Niels

**Comment by petrbrzek** [comment]
I haven't tried it yet. But if it's working with React Native's TextField it should work with Nachos's Input as well.

**Comment by eduardomoroni** [comment]
Yep, I Do. You can check on: https://travis-ci.org/eduardomoroni/trading-card-manager

**Comment by mattapperson** [comment]
Closing as resolved
