### ISSUE TITLE
npm start crashes after install of nachos-ui

### ISSUE THREAD

**Issue by ajonno** [avocode/nachos-ui#9]
hi, firstly thanks for providing some very cool and handy components!

i installed today to an in-dev project running on RN 0.41.1

```npm start``` crashed with the following error:

**Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ResponderEventPlugin**

Here are the clashing paths in the console error message:
```
~/node_modules/nachos-ui/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/eventPlugins/ResponderEventPlugin.js

~/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/eventPlugins/ResponderEventPlugin.js
```

Any tips on how to resolve would be great.

**Comment by ajonno** [comment]
Any ideas? I'd love to use Nachosui this is just a blocker at moment

**Comment by petrbrzek** [comment]
@ajonno Hi buddy, sorry for not responding, I've been quite busy lately. Can you check if there is only one `react` and `react-native` in your dependencies? `find node_modules -name "react"`

**Comment by mattapperson** [comment]
This issue is being tracked now in #34. Closing.
